name: schema_widget_sample
description: A SchemaWidget sample.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  schema_widget:
    path: ../
  logging:

  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart:


flutter:
  uses-material-design: true
