targets:
  $default:
    builders:
      schema_widget|schema_parser_initiator:
        enabled: true

builders:
  schema_parser_initiator:
    target: ":generator/schema_parser_initiator_builder"
    import: "package:schema_widget/generator/builder_factory.dart"
    builder_factories: ["schemaParserInitiatorBuilder"]
    build_extensions: {".dart": [".schema_parser_initiator.g.part"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen"]
