targets:
  $default:
    builders:
      schema_widget|schema_parser_initiator:
        enabled: true
      schema_widget|type_schema_parser_test:
        enabled: true
      schema_widget|type_schema_parser_documentation:
        enabled: true

builders:
  schema_parser_initiator:
    target: ":generator/schema_parser_initiator_builder"
    import: "package:schema_widget/generator/builder_factory.dart"
    builder_factories: ["schemaParserInitiatorBuilder"]
    build_extensions: {".dart": [".schema_parser_initiator.g.part"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen"]
  type_schema_parser_test:
    target: ":generator/type_schema_parser_test_builder"
    import: "package:schema_widget/generator/builder_factory.dart"
    builder_factories: ["typeSchemaParserTestBuilder"]
    build_extensions: {".test.schema.json": [".type_schema_parser_test.g.part"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen"]
  type_schema_parser_documentation:
    target: ":generator/type_schema_parser_support_builder"
    import: "package:schema_widget/generator/builder_factory.dart"
    builder_factories: ["typeSchemaParserSupportBuilder"]
    build_extensions: {".dart": ["../TYPE_SCHEMA_PARSER_SUPPORT.md"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen"]
