name: schema_widget
description: The schema_widget flutter package is a widget generator based on
  JSON parsers capable of producing complex screens and using custom business
  rules.
version: 2.0.0-beta.0
homepage: https://github.com/Legytma/schema_widget

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

legytma_schema:
  version: 3.0.0

dependencies:
  flutter:
    sdk: flutter
  logging: ^0.11.4
  get_it: ^4.0.4
  json_schema: ^2.2.1
  http: ^0.12.2
  build: ^1.3.0
  source_gen: ^0.9.6
  path_provider: ^1.6.14
  flutter_cache_manager: ^1.4.2
  rxdart: ^0.24.1
  analyzer: ^0.39.17
  glob: ^1.2.0
  path: ^1.8.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  effective_dart: ^1.2.4
  build_test: ">=1.0.0"
  build_runner: ^1.10.2
  #  driver_extensions: ^1.2.0+1
  #  test:
  dependency_validator: ^1.5.0

#flutter_icons:
#  android: true
#  ios: true
#  image_path: "assets/images/movie_icon.png"
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/schema/
    - assets/schema/widget/
