name: schema_widget
description: A Flutter package for dynamic widget creation.
version: 1.0.0-0
homepage: https://github.com/Legytma/schema_widget

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.17.5 <2.0.0"

legytma_schema:
  version: 2.0.0

dependencies:
  flutter:
    sdk: flutter
  logging: ^0.11.4
  get_it: ^4.0.4
  json_schema: ^2.2.1
#    path: C:/Users/windo/Documents/Flutter/json_schema
  http: ^0.12.2
  build: ^1.3.0
  source_gen: ^0.9.6
  path_provider: ^1.6.11
  flutter_cache_manager: ^1.4.1
  rxdart: ^0.24.1
  analyzer: ^0.39.15
  glob: ^1.2.0
  path: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  effective_dart: ^1.2.4
  build_test: '>=1.0.0'
  build_runner: ^1.10.0
#  driver_extensions: ^1.2.0+1
#  test:
  dependency_validator: ^1.5.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

#flutter_icons:
#  android: true
#  ios: true
#  image_path: "assets/images/movie_icon.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/LegytmaSchemas/schema/
    - assets/LegytmaSchemas/schema/widget/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
