name: Dart CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Dart and Flutter Analizer'
        uses: axel-op/dart-package-analyzer@v2
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Dart and Flutter Package Publisher'
        uses: k-paxian/dart-package-publisher@v1.2
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
