name: Flutter CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: 'Setup Java'
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: 'Setup flutter'
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: 'Install dependencies'
        run: flutter pub get

      - name: 'Build example'
        run: flutter build aot --target=example/lib/main.dart

      - name: 'Flutter analyze'
        run: flutter analyze

      - name: 'Flutter test coverage'
        run: flutter test --coverage test

      - name: 'Coverage'
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}} # not required for public repos
          file: ./coverage/lcov.info

      - name: 'Dart and Flutter Analizer'
        uses: axel-op/dart-package-analyzer@v2
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Setup Pub Credentials'
        shell: bash
        env:
          PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
          PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
          PUB_DEV_PUBLISH_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}
          PUB_DEV_PUBLISH_EXPIRATION: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
        run: |
          sh ./pub_login.sh

      - name: 'Check Publish Warnings'
        run: flutter pub pub publish --dry-run

      - name: 'Publish Package'
        run: flutter pub pub publish -f
